name: "Build and check Lexilla on Linux"

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                cpp_compiler: [g++, clang++]

        steps:
        - uses: actions/checkout@v3
        - name: Install Scintilla source
          run: |
              (cd .. && wget --no-verbose https://www.scintilla.org/scintilla500.zip)
              (cd .. && unzip scintilla500.zip)
        - name: Unit Test
          run: (cd test/unit && make DEBUG=1 CXX=${{matrix.cpp_compiler}} test)
        - name: Build Lexilla
          run: (cd src && make DEBUG=1 CXX=${{matrix.cpp_compiler}})
        - uses: actions/upload-artifact@v3
          with:
              name: liblexilla.so
              path: bin/liblexilla.so
        - name: Test lexing and folding
          run: (cd test && make DEBUG=1 CXX=${{matrix.cpp_compiler}} test)
        - name: CheckLexilla C Example
          run: (cd examples/CheckLexilla && make DEBUG=1 check)
        - name: SimpleLexer Example
          run: (cd examples/SimpleLexer && make DEBUG=1 CXX=${{matrix.cpp_compiler}} check)
